// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:572f81c4-7f1e-4aaf-9177-8120650628ea',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'xteamintegrationtest-hosting-mobilehub-1813410687',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3uznz6rfrgy5a.cloudfront.net',
    'aws_mobile_analytics_app_id': '0defeb1f1cdf4fcb864282190a355fd0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c88e3e3f-581d-4905-868b-e250e08485ac',
    'aws_project_name': 'xteamintegrationtest',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'xteamintegrationtest-mobilehub-1813410687',
}

export default awsmobile;
